// GET /api/ibm/forecast?mint=<mint>&interval=5m&horizon=24[&model=<id>]
// --------------------------------------------------------------------------
// The "Granite Oracle": forecasts a Solana token's price with IBM watsonx
// Granite Time Series foundation models, then narrates the outlook with IBM
// Granite LLM. Real APIs end to end — Birdeye OHLCV → watsonx TS forecast →
// watsonx chat. No fabricated candles, no mock forecast.
//
// Response:
// {
//   mint, interval, freq, model, horizon,
//   history:  [{ t, c }],         // recent closes (unix seconds)
//   forecast: [{ t, c }],         // Granite-projected closes
//   last_price, forecast_price, change_pct, sentiment,
//   commentary,                   // Granite LLM analyst note (or null)
//   generated_at
// }

import { cors, json, method, wrap, error } from '../_lib/http.js';
import { limits, clientIp } from '../_lib/rate-limit.js';
import { fetchBirdeyeOhlcv, birdeyeConfigured } from '../_lib/birdeye.js';
import {
	watsonxConfig,
	watsonxForecast,
	watsonxChatComplete,
	tsModelSpec,
	DEFAULT_TS_MODEL,
} from '../_lib/watsonx.js';

// Forecasting-friendly intervals: each maps to its spacing in seconds and the
// pandas offset alias the watsonx TS API expects for `freq`.
const INTERVALS = {
	'5m': { sec: 300, freq: '5min', birdeye: '5m' },
	'15m': { sec: 900, freq: '15min', birdeye: '15m' },
	'1H': { sec: 3600, freq: '1h', birdeye: '1H' },
	'1D': { sec: 86400, freq: '1D', birdeye: '1D' },
};

function normalizeInterval(raw) {
	if (!raw) return '15m';
	const v = String(raw).trim();
	if (INTERVALS[v]) return v;
	const lower = { '1h': '1H', '1d': '1D' }[v.toLowerCase()];
	return lower && INTERVALS[lower] ? lower : INTERVALS[v.toLowerCase()] ? v.toLowerCase() : '15m';
}

function isPlausibleMint(s) {
	return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(s);
}

function sentimentOf(changePct) {
	if (changePct > 0.5) return 'bullish';
	if (changePct < -0.5) return 'bearish';
	return 'neutral';
}

async function graniteCommentary(cfg, ctx) {
	// Best-effort: a failed narration must never sink the forecast itself.
	const system =
		'You are the Granite Oracle, an on-chain market analyst speaking through a 3D avatar. ' +
		'You are handed a price forecast generated by IBM Granite time-series foundation models. ' +
		'In 2-3 vivid but measured sentences, read the projected move for the user. ' +
		'Make clear this is a model projection, not financial advice or a guarantee.';
	const user =
		`Token mint ${ctx.mint} on Solana. Interval ${ctx.interval}. ` +
		`Last price ${ctx.last_price}. Granite projects ${ctx.forecast_price} over the next ` +
		`${ctx.horizon} steps (${ctx.change_pct >= 0 ? '+' : ''}${ctx.change_pct.toFixed(2)}%). ` +
		`Sentiment: ${ctx.sentiment}.`;
	try {
		const { text } = await watsonxChatComplete(cfg, {
			messages: [
				{ role: 'system', content: system },
				{ role: 'user', content: user },
			],
			maxTokens: 180,
			temperature: 0.6,
		});
		return text?.trim() || null;
	} catch (e) {
		console.warn('[ibm/forecast] Granite commentary failed:', e.message);
		return null;
	}
}

export default wrap(async (req, res) => {
	if (cors(req, res, { methods: 'GET,OPTIONS', origins: '*' })) return;
	if (!method(req, res, ['GET'])) return;

	const rl = await limits.forecastIp(clientIp(req));
	if (!rl.success) return error(res, 429, 'rate_limited', 'too many forecast requests');

	const cfg = watsonxConfig();
	if (!cfg.configured)
		return error(res, 503, 'not_configured', 'IBM watsonx is not configured on this server');
	if (!birdeyeConfigured())
		return error(res, 503, 'not_configured', 'On-chain data provider is not configured');

	const params = new URL(req.url, 'http://x').searchParams;
	const mint = (params.get('mint') || '').trim();
	if (!isPlausibleMint(mint))
		return error(res, 400, 'bad_mint', 'mint must be a base58 Solana address (32–44 chars)');

	const interval = normalizeInterval(params.get('interval'));
	const { sec: intervalSec, freq, birdeye } = INTERVALS[interval];

	const model = params.get('model') || DEFAULT_TS_MODEL;
	const spec = tsModelSpec(model);
	if (!spec) return error(res, 400, 'bad_model', `unknown model "${model}"`);

	const horizon = Math.max(1, Math.min(parseInt(params.get('horizon') || '24', 10) || 24, spec.horizon));

	// Pull enough history to satisfy the model's context window, with headroom
	// for gaps/illiquid candles. Birdeye caps windows at 30 days.
	const nowSec = Math.floor(Date.now() / 1000);
	const lookback = Math.min(Math.ceil(intervalSec * spec.context * 1.6), 30 * 86400);
	const from = nowSec - lookback;

	let candles;
	try {
		candles = await fetchBirdeyeOhlcv({ mint, interval: birdeye, from, to: nowSec });
	} catch (e) {
		return error(res, e.status || 502, 'upstream_error', e.message);
	}

	candles.sort((a, b) => a.t - b.t);
	if (candles.length < spec.context) {
		return error(
			res,
			422,
			'insufficient_data',
			`This token has only ${candles.length} ${interval} candles; ${spec.context} are needed ` +
				`for ${spec.id}. Try a more liquid token or a finer interval.`,
		);
	}

	const timestamps = candles.map((c) => new Date(c.t * 1000).toISOString());
	const closes = candles.map((c) => c.c);

	let forecast;
	try {
		forecast = await watsonxForecast(cfg, {
			timestamps,
			values: closes,
			freq,
			predictionLength: horizon,
			model,
		});
	} catch (e) {
		if (e.code === 'insufficient_data')
			return error(res, 422, 'insufficient_data', e.message);
		console.error('[ibm/forecast] watsonx forecast failed:', e.message);
		return error(res, 502, 'upstream_error', `Granite forecast failed: ${e.message}`);
	}

	const lastT = candles[candles.length - 1].t;
	const fcPoints = forecast.values.map((c, i) => {
		const iso = forecast.timestamps[i];
		const t = iso ? Math.floor(Date.parse(iso) / 1000) : lastT + (i + 1) * intervalSec;
		return { t: Number.isFinite(t) ? t : lastT + (i + 1) * intervalSec, c };
	});

	const lastPrice = closes[closes.length - 1];
	const forecastPrice = fcPoints[fcPoints.length - 1].c;
	const changePct = lastPrice ? ((forecastPrice - lastPrice) / lastPrice) * 100 : 0;
	const sentiment = sentimentOf(changePct);

	// Trim the history we return for charting — the model read 512+ points but the
	// client only needs recent context to draw the lead-in.
	const HISTORY_OUT = 96;
	const history = candles.slice(-HISTORY_OUT).map((c) => ({ t: c.t, c: c.c }));

	const commentary = await graniteCommentary(cfg, {
		mint,
		interval,
		last_price: lastPrice,
		forecast_price: forecastPrice,
		change_pct: changePct,
		horizon,
		sentiment,
	});

	return json(
		res,
		200,
		{
			mint,
			interval,
			freq,
			model: forecast.model,
			horizon,
			history,
			forecast: fcPoints,
			last_price: lastPrice,
			forecast_price: forecastPrice,
			change_pct: changePct,
			sentiment,
			commentary,
			generated_at: new Date().toISOString(),
		},
		{ 'cache-control': 'public, max-age=20, s-maxage=30' },
	);
});
