// Forge — text / image / multi-view → 3D generator (browser client).
import { skeletonHTML, errorStateHTML, ensureStateKitStyles } from './shared/state-kit.js';
import { showSharePanel } from './shared/share.js';
import { stampGlbAttribution } from './shared/glb-attribution.js';
ensureStateKitStyles();
//
// Drives /api/forge. Three paths share one polling loop:
//   • Text → 3D — POST a prompt; FLUX paints a reference image, then TRELLIS
//     reconstructs the mesh.
//   • Image / multi-view → 3D — the user adds 1–4 photos of one object from
//     different angles. Each photo is uploaded straight to object storage via a
//     presigned URL (/api/forge-upload), then their public URLs are POSTed as
//     image_urls. With >1 view the backend fuses them (multi-view conditioning)
//     and reports how many views it used + which backend handled it.
//   • Sketch → 3D — one drawing + a required prompt naming what it depicts,
//     generated by the self-host TripoSG scribble engine (path: 'sketch').
//     The mode tab only appears when the catalog reports that engine live.
//
// State transitions are driven by real API responses; the only timer is the
// honest elapsed counter. Nothing fakes progress.

const POLL_INTERVAL_MS = 2500;
const MAX_POLL_MS = 5 * 60 * 1000; // generous ceiling for reconstruction
const MAX_VIEWS = 4;
const VIEW_LABELS = ['Front', 'Back', 'Left', 'Right'];
const MAX_UPLOAD_BYTES = 8 * 1024 * 1024;
const ACCEPTED_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp']);

const els = {
	form: document.getElementById('composer'),
	prompt: document.getElementById('prompt'),
	aspect: document.getElementById('aspect'),
	generate: document.getElementById('generate'),
	generateLabel: document.getElementById('generate-label'),
	examples: document.getElementById('examples'),
	stage: document.getElementById('stage'),
	modeSwitch: document.getElementById('mode-switch'),
	textPane: document.getElementById('text-pane'),
	imagePane: document.getElementById('image-pane'),
	viewsGrid: document.getElementById('views-grid'),
	fileInput: document.getElementById('view-file-input'),
	imagePrompt: document.getElementById('image-prompt'),
	sketchPane: document.getElementById('sketch-pane'),
	sketchGrid: document.getElementById('sketch-grid'),
	sketchFileInput: document.getElementById('sketch-file-input'),
	sketchPrompt: document.getElementById('sketch-prompt'),
	states: {
		empty: document.getElementById('state-empty'),
		generating: document.getElementById('state-generating'),
		result: document.getElementById('state-result'),
		error: document.getElementById('state-error'),
		unconfigured: document.getElementById('state-unconfigured'),
	},
	genPreview: document.getElementById('gen-preview'),
	genMeta: document.getElementById('gen-meta'),
	genProgress: document.getElementById('gen-progress'),
	genProgressFill: document.getElementById('gen-progress-fill'),
	steps: {
		image: document.getElementById('step-image'),
		mesh: document.getElementById('step-mesh'),
		finish: document.getElementById('step-finish'),
	},
	cancel: document.getElementById('cancel'),
	viewer: document.getElementById('viewer'),
	viewerShell: document.getElementById('viewer-shell'),
	cinema: document.getElementById('cinema'),
	resultLabel: document.getElementById('result-label'),
	resultViews: document.getElementById('result-views'),
	verdict: document.getElementById('verdict'),
	download: document.getElementById('download'),
	again: document.getElementById('again'),
	refine: document.getElementById('refine'),
	refineLabel: document.getElementById('refine-label'),
	retry: document.getElementById('retry'),
	viewsCounter: document.getElementById('views-counter'),
	viewsCounterText: document.getElementById('views-counter-text'),
	viewsPips: document.getElementById('views-pips'),
	sketchReqTag: document.getElementById('sketch-req-tag'),
	generateAnyway: document.getElementById('generate-anyway'),
	errorMessage: document.getElementById('error-message'),
	forgeShareBtn: document.getElementById('forge-share-btn'),
	segmentBtn: document.getElementById('forge-segment-btn'),
	creations: document.getElementById('creations'),
	creationsGrid: document.getElementById('creations-grid'),
	creationsCount: document.getElementById('creations-count'),
	// Quality tier + generation engine + BYOK key.
	tier: document.getElementById('tier'),
	engine: document.getElementById('engine'),
	byokRow: document.getElementById('byok-row'),
	byokLabel: document.getElementById('byok-label'),
	byokHint: document.getElementById('byok-hint'),
	providerKey: document.getElementById('provider-key'),
	estimate: document.getElementById('estimate'),
};

let aspectRatio = '1:1';
let elapsedTimer = null;
let pollAbort = false;
let mode = 'text'; // 'text' | 'image' | 'sketch' — input mode (prompt vs photos vs drawing)
let lastJob = null; // { prompt, imageUrls } — for retry
let currentCreationId = null;
// The quality tier the on-screen result was produced at — drives the "Refine"
// affordance, which re-runs the same job exactly one tier higher.
let currentResultTier = null;

// Quality tiers, lowest → highest. Refine walks one step up this ladder.
const TIER_ORDER = ['draft', 'standard', 'high'];
const TIER_LABELS = { draft: 'Draft', standard: 'Standard', high: 'High' };
function nextTierAfter(tier) {
	const i = TIER_ORDER.indexOf(tier);
	return i >= 0 && i < TIER_ORDER.length - 1 ? TIER_ORDER[i + 1] : null;
}

// Generation route + quality. `genPath` is the task's image|geometry axis;
// `genBackend` names the provider; both come from the selected engine button.
// The catalog (tiers + backends + cost/time matrix) is fetched once on load.
let catalog = null;
// Live backend health (/api/forge?health) — probed upstream auth/quota, not
// just env presence. Null until the probe returns; the buttons render
// optimistically from the catalog and tighten when health lands.
let health = null;
let selectedTier = 'standard';
let selectedEngine = { id: 'trellis', path: 'image', backend: 'trellis', byok: null, polyControl: false };
// Once the user deliberately picks an engine we stop auto-selecting the
// catalog's per-tier default (e.g. the free NVIDIA lane on draft) under them.
let userPickedEngine = false;
// BYOK key held only in memory for this session — sent per request, never stored
// by the page. Signed-in users can instead save it server-side in Account.
let providerKey = '';

// Cinema mode — distraction-free fullscreen turntable for recording/sharing.
// Toggled by the result-bar button or F; Esc always exits. Rotation slows so
// the loop reads as deliberate, not busy.
let cinemaOn = false;
function setCinema(on) {
	if (!els.cinema || on === cinemaOn) return;
	cinemaOn = on;
	els.states.result.classList.toggle('is-cinema', on);
	document.body.classList.toggle('forge-cinema', on);
	els.cinema.setAttribute('aria-pressed', String(on));
	els.viewer.setAttribute('rotation-per-second', on ? '10deg' : '18deg');
}

// Friendly engine labels + where to mint a key, keyed by backend id.
const ENGINE_LABELS = { nvidia: 'Free', trellis: 'Fast', meshy: 'Meshy', tripo: 'Tripo', hunyuan3d: 'Hunyuan3D', triposg: 'TripoSG' };
const KEY_HINTS = {
	meshy: { label: 'Meshy AI', url: 'https://www.meshy.ai/settings/api' },
	tripo: { label: 'Tripo AI', url: 'https://platform.tripo3d.ai/api-keys' },
};

// One entry per reference-view slot. `state` drives the slot's rendered region;
// `url` is the durable public URL (what we send); `objectUrl` is the local
// preview blob, revoked when the slot is cleared.
const slots = VIEW_LABELS.map(() => ({
	state: 'empty',
	url: null,
	objectUrl: null,
	errorMsg: '',
}));

// File picker target: the slot index the picker was opened for, or null to fill
// from the first free slot.
let pickerTarget = null;

// Sketch mode input — one drawing, same lifecycle as a view slot.
const sketch = { state: 'empty', url: null, objectUrl: null, errorMsg: '' };

// Stable anonymous handle for this browser. /forge has no login, so durable
// creations + the gallery are scoped to this id (hashed server-side). Sent on
// every request via the x-forge-client header.
const CLIENT_ID = (() => {
	const KEY = 'forge:cid';
	try {
		let id = localStorage.getItem(KEY);
		if (!id) {
			id =
				crypto?.randomUUID?.() ||
				`c-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
			localStorage.setItem(KEY, id);
		}
		return id;
	} catch {
		// Private mode / storage blocked — fall back to an ephemeral per-load id.
		return `c-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
	}
})();

const CLIENT_HEADERS = { 'x-forge-client': CLIENT_ID };

const REDUCED_MOTION =
	typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

function showState(name) {
	for (const [key, node] of Object.entries(els.states)) {
		node.classList.toggle('is-hidden', key !== name);
	}
	// Leaving the result state always leaves cinema mode with it.
	if (name !== 'result' && cinemaOn) setCinema(false);
}

function setStep(step, state) {
	if (els.steps[step]) els.steps[step].dataset.state = state;
	// The scanline sweep runs exactly while the mesh step is live.
	if (step === 'mesh') els.genPreview.classList.toggle('is-reconstructing', state === 'active');
}

function setStepLabel(step, text) {
	const node = els.steps[step]?.querySelector('span:last-child');
	if (node) node.textContent = text;
}

// The typical end-to-end time for the current engine+tier, straight from the
// catalog's real estimate matrix (estimateEtaSeconds). Null when no catalog or
// estimate exists — the meter then runs indeterminate rather than inventing a
// duration.
function currentEtaSeconds() {
	if (!catalog) return null;
	const backend = catalog.backends?.find((b) => b.id === selectedEngine.backend);
	const est = (backend?.estimates?.[selectedEngine.path] || []).find(
		(e) => e.tier === selectedTier,
	);
	return Number(est?.eta_seconds) > 0 ? Number(est.eta_seconds) : null;
}

// Map real elapsed seconds onto an honest fill fraction. The curve approaches
// 1 asymptotically and is capped below it, so the bar can never reach full on
// time alone — only a real finished GLB sets it to 100% (see markDone). At
// elapsed = typical the fill sits ~0.78; it keeps creeping past that but never
// claims completion.
function honestFill(elapsedS, typicalS) {
	const frac = 1 - Math.exp(-elapsedS / (typicalS * 0.66));
	return Math.min(frac, 0.95);
}

function setProgress(pct) {
	if (!els.genProgressFill || !els.genProgress) return;
	const clamped = Math.max(0, Math.min(100, pct));
	els.genProgressFill.style.width = `${clamped}%`;
	els.genProgress.setAttribute('aria-valuenow', String(Math.round(clamped)));
}

function startElapsed() {
	const started = performance.now();
	stopElapsed();
	const typical = currentEtaSeconds();
	// Reset the meter to a clean running state for this job.
	if (els.genProgress) {
		els.genProgress.dataset.done = 'false';
		els.genProgress.dataset.over = 'false';
		els.genProgress.dataset.indeterminate = typical ? 'false' : 'true';
	}
	setProgress(0);
	const tick = () => {
		const s = Math.floor((performance.now() - started) / 1000);
		if (typical) {
			const over = s > typical;
			setProgress(honestFill(s, typical) * 100);
			if (els.genProgress) els.genProgress.dataset.over = String(over);
			els.genMeta.innerHTML = over
				? `Elapsed <strong>${s}s</strong> · longer than usual, still working`
				: `Elapsed <strong>${s}s</strong> · ~${typical}s typical`;
		} else {
			// Unknown duration — the bar travels (indeterminate) and we report only
			// the honest elapsed count.
			els.genMeta.innerHTML = `Elapsed <strong>${s}s</strong>`;
		}
	};
	tick();
	elapsedTimer = window.setInterval(tick, 1000);
}

// Snap the meter to a finished, successful state — the only path to 100%.
function markProgressDone() {
	if (!els.genProgress) return;
	els.genProgress.dataset.indeterminate = 'false';
	els.genProgress.dataset.over = 'false';
	els.genProgress.dataset.done = 'true';
	setProgress(100);
}

function stopElapsed() {
	if (elapsedTimer) {
		window.clearInterval(elapsedTimer);
		elapsedTimer = null;
	}
}

function setBusy(busy) {
	els.generate.disabled = busy;
	els.generateLabel.textContent = busy ? 'Forging…' : 'Generate';
}

function sleep(ms) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

// Mode switching --------------------------------------------------------------

function setMode(next) {
	if (next !== 'text' && next !== 'image' && next !== 'sketch') return;
	mode = next;
	els.textPane.classList.toggle('is-hidden', mode !== 'text');
	els.imagePane.classList.toggle('is-hidden', mode !== 'image');
	els.sketchPane?.classList.toggle('is-hidden', mode !== 'sketch');
	els.examples.classList.toggle('is-hidden', mode !== 'text');
	for (const b of els.modeSwitch.querySelectorAll('button')) {
		b.setAttribute('aria-selected', String(b.dataset.mode === mode));
	}
	// Sketch serves through its own engine set (TripoSG) — rebuild the selector
	// so each mode only offers engines that can actually take its input.
	if (catalog) buildEngineButtons();
	updateAspectVisibility();
	if (mode === 'text') els.prompt.focus();
	if (mode === 'sketch' && sketch.state === 'empty') sketchSlotEl()?.focus();
}

// Aspect ratio only shapes the synthesized reference image — irrelevant when
// the user supplies their own photos OR uses the geometry-first path (which
// never paints an intermediate image).
function updateAspectVisibility() {
	if (!els.aspect) return;
	const relevant = mode === 'text' && selectedEngine.path === 'image';
	els.aspect.classList.toggle('is-hidden', !relevant);
}

// Quality tier + engine ------------------------------------------------------

// Fetch the tier/backend/cost catalog once, then build the engine selector from
// the backends that are live (platform-configured) or BYOK (always selectable).
async function loadCatalog() {
	try {
		const res = await fetch('/api/forge?catalog=1', { headers: CLIENT_HEADERS });
		catalog = await res.json().catch(() => null);
	} catch {
		catalog = null;
	}
	if (!catalog || !Array.isArray(catalog.backends)) {
		// No catalog (older deploy) — hide the controls; defaults still work.
		els.engine?.closest('#forge-quality')?.classList.add('is-hidden');
		return;
	}
	buildEngineButtons();
	selectTier(selectedTier);
	revealSketchMode();
	loadHealth();
}

// Sketch→3D needs the self-host TripoSG worker — the tab stays hidden unless
// the catalog reports that engine configured, so there is no dead mode on
// deployments without it.
function revealSketchMode() {
	const tab = els.modeSwitch?.querySelector('button[data-mode="sketch"]');
	if (!tab) return;
	const live = catalog.backends.some((b) => b.paths?.includes('sketch') && b.configured);
	tab.hidden = !live;
	if (live) buildSketchSlot();
}

// Live-probe the backends in the background, then tighten the engine buttons:
// a lane whose upstream is down gets disabled with the real reason instead of
// failing after the user has already typed a prompt and clicked Generate.
async function loadHealth() {
	try {
		const res = await fetch('/api/forge?health=1', { headers: CLIENT_HEADERS });
		const body = await res.json().catch(() => null);
		health = body && body.backends ? body : null;
	} catch {
		health = null;
	}
	if (health) updateEngineAvailability();
}

function buildEngineButtons() {
	if (!els.engine) return;
	// Each mode offers only the engines that take its input: sketch mode shows
	// the sketch-path engines (TripoSG); text/photo modes hide sketch-only ones.
	const usable = catalog.backends.filter((b) => {
		if (!(b.configured || b.byok)) return false;
		const sketchOnly = Array.isArray(b.paths) && b.paths.every((p) => p === 'sketch');
		return mode === 'sketch' ? b.paths.includes('sketch') : !sketchOnly;
	});
	els.engine.innerHTML = '';
	for (const b of usable) {
		// Each backend exposes the geometry-first path when it supports it; the
		// image-intermediate engines (TRELLIS, Hunyuan3D) keep the image path.
		const path =
			mode === 'sketch' ? 'sketch' : b.paths.includes('geometry') ? 'geometry' : 'image';
		const btn = document.createElement('button');
		btn.type = 'button';
		btn.dataset.engine = b.id;
		btn.dataset.path = path;
		btn.dataset.backend = b.id;
		btn.dataset.byok = b.byok || '';
		btn.dataset.poly = String(Boolean(b.poly_control));
		// Text-only engines (the free NVIDIA TRELLIS preview) can't take photos;
		// updateEngineAvailability() disables them while reference views are set.
		btn.dataset.userimages = String(b.user_images !== false);
		btn.textContent = ENGINE_LABELS[b.id] || b.label;
		btn.title = `${b.label} — ${b.blurb}`;
		btn.setAttribute('aria-pressed', String(b.id === selectedEngine.backend));
		els.engine.appendChild(btn);
	}
	// If the previously-selected engine isn't usable, fall back to the first.
	if (!usable.some((b) => b.id === selectedEngine.backend)) {
		const first = els.engine.querySelector('button');
		if (first) selectEngine(first, true);
	}
	updateEngineAvailability();
}

// Keep the engine buttons honest about the current input mode, and keep the
// selection on the catalog's per-tier default until the user picks one.
//   • With reference photos attached, text-only engines are disabled (the free
//     NVIDIA TRELLIS preview rejects user images) and a selected one bounces to
//     the default photo engine.
//   • With no photos and no explicit user choice, the tier's default engine is
//     applied — which is what routes draft prompts onto the free lane.
function updateEngineAvailability() {
	if (!els.engine || !catalog) return;
	const hasPhotos = slots.some((s) => s.state === 'uploaded' || s.state === 'uploading');
	let bounceTo = null;
	for (const btn of els.engine.querySelectorAll('button')) {
		const textOnly = btn.dataset.userimages === 'false';
		const b = catalog.backends?.find((x) => x.id === btn.dataset.backend);
		// Live health beats the catalog's env-presence flag: a lane whose
		// upstream auth/billing probe failed is disabled with the real reason.
		const lane = health?.backends?.[btn.dataset.backend];
		const laneDown = lane && (lane.status === 'down' || lane.status === 'unconfigured');
		const laneBusy = lane && lane.status === 'degraded';
		const blocked = (textOnly && hasPhotos) || laneDown;
		btn.disabled = blocked;
		btn.setAttribute('aria-disabled', String(blocked));
		btn.dataset.health = lane ? lane.status : '';
		if (laneDown) {
			btn.title = `${b?.label || btn.dataset.backend} — temporarily unavailable: ${lane.message}`;
		} else if (blocked) {
			btn.title = 'This engine generates from text prompts only — clear the reference views to use it.';
		} else if (b) {
			btn.title = laneBusy
				? `${b.label} — busy right now: ${lane.message}`
				: `${b.label} — ${b.blurb}`;
		}
		if (blocked && btn.dataset.backend === selectedEngine.backend) bounceTo = true;
	}
	const defaultId = catalog.default_backend_for_tier?.[selectedTier]?.[selectedEngine.path] ?? null;
	if (bounceTo) {
		// Forced move: the selected engine can't serve photos. Prefer the standing
		// photo default, else the first enabled button.
		const fallbackId = catalog.default_backend?.image || 'trellis';
		const target =
			els.engine.querySelector(`button[data-backend="${fallbackId}"]:not(:disabled)`) ||
			els.engine.querySelector('button:not(:disabled)');
		if (target) selectEngine(target);
	} else if (!userPickedEngine && !hasPhotos && defaultId && defaultId !== selectedEngine.backend) {
		const target = els.engine.querySelector(`button[data-backend="${defaultId}"]:not(:disabled)`);
		if (target) selectEngine(target);
	}
}

function selectEngine(btn, silent) {
	if (!btn) return;
	selectedEngine = {
		id: btn.dataset.engine,
		path: btn.dataset.path,
		backend: btn.dataset.backend,
		byok: btn.dataset.byok || null,
		polyControl: btn.dataset.poly === 'true',
	};
	for (const b of els.engine.querySelectorAll('button')) {
		b.setAttribute('aria-pressed', String(b === btn));
	}
	updateByokRow();
	updateAspectVisibility();
	if (!silent) updateEstimate();
}

// Show the key field only for BYOK engines, with provider-specific hint + link.
function updateByokRow() {
	if (!els.byokRow) return;
	const byok = selectedEngine.byok;
	els.byokRow.classList.toggle('is-hidden', !byok);
	if (!byok) return;
	const hint = KEY_HINTS[byok];
	els.byokLabel.textContent = `${hint?.label || byok} key`;
	els.providerKey.placeholder = `Your ${hint?.label || byok} API key (kept in this browser)`;
	els.byokHint.innerHTML = hint
		? `Geometry-first uses your own ${hint.label} key. <a href="${hint.url}" target="_blank" rel="noopener">Get a key →</a> Signed-in users can save it in Account instead.`
		: 'This engine needs your own API key.';
}

function selectTier(tierId) {
	if (!['draft', 'standard', 'high'].includes(tierId)) return;
	selectedTier = tierId;
	for (const b of els.tier.querySelectorAll('button')) {
		b.setAttribute('aria-pressed', String(b.dataset.tier === tierId));
	}
	// Tier changes can move the default engine (draft prefers the free lane).
	updateEngineAvailability();
	updateEstimate();
}

// Render the honest time/cost/poly estimate for the current engine + tier from
// the catalog. No fabricated numbers — everything comes from /api/forge?catalog.
function updateEstimate() {
	if (!els.estimate || !catalog) return;
	const backend = catalog.backends.find((b) => b.id === selectedEngine.backend);
	const tierMeta = catalog.tiers.find((t) => t.id === selectedTier);
	if (!backend || !tierMeta) {
		els.estimate.textContent = '';
		return;
	}
	const est = (backend.estimates?.[selectedEngine.path] || []).find((e) => e.tier === selectedTier);
	// Holder-readable, not pipeline-internal: say how long it usually takes and
	// what the engine does, in plain words. The mechanism ("builds from a
	// reference image") replaces jargon like "image-intermediate · fast path".
	const parts = [`<strong>${tierMeta.label}</strong>`];
	if (est?.eta_seconds) parts.push(`usually ~${est.eta_seconds}s`);
	if (est && est.credits != null) parts.push(`~${est.credits} credits`);
	if (backend.poly_control) parts.push(`up to ${tierMeta.polycount.toLocaleString()} polygons`);
	if (selectedEngine.path === 'geometry') parts.push('shapes geometry straight from the prompt');
	else if (selectedEngine.path === 'sketch') parts.push('untextured geometry from your sketch');
	else parts.push('builds from a reference image');
	els.estimate.innerHTML = parts.join(' · ');
}

// View slots ------------------------------------------------------------------

function buildSlots() {
	els.viewsGrid.innerHTML = '';
	slots.forEach((_, i) => {
		const slot = document.createElement('div');
		slot.className = 'view-slot';
		slot.dataset.index = String(i);
		slot.tabIndex = 0;
		slot.setAttribute('role', 'button');

		slot.innerHTML = `
			<div class="vs-empty">
				<span class="vs-icon" aria-hidden="true">＋</span>
				<span class="vs-label">${VIEW_LABELS[i]}</span>
			</div>
			<div class="vs-uploading">
				<div class="shimmer" aria-hidden="true"></div>
				<span>Uploading…</span>
			</div>
			<img class="vs-thumb" alt="" />
			<span class="vs-badge">${VIEW_LABELS[i]}</span>
			<button type="button" class="vs-remove" aria-label="Remove ${VIEW_LABELS[i]} view">×</button>
			<div class="vs-error">
				<span class="vs-error-msg">Upload failed</span>
				<button type="button" class="vs-retry">Retry</button>
			</div>`;

		// Remove (stop click from also re-opening the picker).
		slot.querySelector('.vs-remove').addEventListener('click', (e) => {
			e.stopPropagation();
			clearSlot(i);
		});
		// Retry re-opens the picker for this slot.
		slot.querySelector('.vs-retry').addEventListener('click', (e) => {
			e.stopPropagation();
			openPicker(i);
		});

		// Click empty/error → browse for this slot.
		slot.addEventListener('click', () => {
			if (slots[i].state === 'empty' || slots[i].state === 'error') openPicker(i);
		});
		slot.addEventListener('keydown', (e) => {
			if (e.key === 'Enter' || e.key === ' ') {
				e.preventDefault();
				if (slots[i].state === 'empty' || slots[i].state === 'error') openPicker(i);
			}
		});

		// Drag to reorder (uploaded slots only).
		slot.addEventListener('dragstart', (e) => {
			if (slots[i].state !== 'uploaded') {
				e.preventDefault();
				return;
			}
			e.dataTransfer.setData('application/x-forge-slot', String(i));
			e.dataTransfer.effectAllowed = 'move';
			slot.classList.add('dragging');
		});
		slot.addEventListener('dragend', () => slot.classList.remove('dragging'));

		// Drop target — accepts files OR a dragged thumbnail (reorder).
		slot.addEventListener('dragover', (e) => {
			e.preventDefault();
			e.dataTransfer.dropEffect = e.dataTransfer.types.includes('application/x-forge-slot')
				? 'move'
				: 'copy';
			slot.classList.add('drop-target');
		});
		slot.addEventListener('dragleave', () => slot.classList.remove('drop-target'));
		slot.addEventListener('drop', (e) => {
			e.preventDefault();
			slot.classList.remove('drop-target');
			const from = e.dataTransfer.getData('application/x-forge-slot');
			if (from !== '') {
				swapSlots(Number(from), i);
			} else if (e.dataTransfer.files?.length) {
				handleFiles(i, e.dataTransfer.files);
			}
		});

		els.viewsGrid.appendChild(slot);
		renderSlot(i);
	});
}

function slotEl(i) {
	return els.viewsGrid.querySelector(`.view-slot[data-index="${i}"]`);
}

// One pip per possible reference view — filled as photos upload.
function buildViewsPips() {
	if (!els.viewsPips || els.viewsPips.childElementCount) return;
	for (let i = 0; i < MAX_VIEWS; i++) {
		const pip = document.createElement('i');
		pip.dataset.filled = 'false';
		els.viewsPips.appendChild(pip);
	}
}

// Live "N of 4 views" readout + pips. Teaches that more views sharpen the mesh,
// so users don't stop at a single photo thinking it's enough.
function updateViewsCounter() {
	if (!els.viewsCounter || !els.viewsCounterText) return;
	const n = slots.filter((s) => s.state === 'uploaded').length;
	const pips = els.viewsPips ? els.viewsPips.children : [];
	for (let i = 0; i < pips.length; i++) pips[i].dataset.filled = String(i < n);
	let tail;
	if (n === 0) tail = ' — add a photo to begin';
	else if (n < MAX_VIEWS) tail = ' · <span class="vc-quality">more views = sharper</span>';
	else tail = ' · <span class="vc-quality">full coverage</span>';
	els.viewsCounterText.innerHTML = `<strong>${n}</strong> of ${MAX_VIEWS} views${tail}`;
}

function renderSlot(i) {
	const el = slotEl(i);
	if (!el) return;
	const s = slots[i];
	el.dataset.state = s.state;
	el.draggable = s.state === 'uploaded';
	// Slot changes flip the input mode (prompt-only ↔ photo), which changes
	// which engines may serve — keep the selector honest in the same frame.
	updateEngineAvailability();
	updateViewsCounter();

	const img = el.querySelector('.vs-thumb');
	if (s.objectUrl) {
		img.src = s.objectUrl;
		img.alt = `${VIEW_LABELS[i]} view`;
	} else {
		img.removeAttribute('src');
		img.alt = '';
	}
	el.querySelector('.vs-error-msg').textContent = s.errorMsg || 'Upload failed';

	const labels = {
		empty: `${VIEW_LABELS[i]} view, empty — add a photo`,
		uploading: `${VIEW_LABELS[i]} view, uploading`,
		uploaded: `${VIEW_LABELS[i]} view, uploaded — drag to reorder`,
		error: `${VIEW_LABELS[i]} view, upload failed`,
	};
	el.setAttribute('aria-label', labels[s.state] || VIEW_LABELS[i]);
}

function clearSlot(i) {
	const s = slots[i];
	if (s.objectUrl) URL.revokeObjectURL(s.objectUrl);
	slots[i] = { state: 'empty', url: null, objectUrl: null, errorMsg: '' };
	renderSlot(i);
}

function swapSlots(a, b) {
	if (a === b) return;
	const tmp = slots[a];
	slots[a] = slots[b];
	slots[b] = tmp;
	renderSlot(a);
	renderSlot(b);
}

function firstFreeSlot() {
	return slots.findIndex((s) => s.state === 'empty' || s.state === 'error');
}

function nextFreeAfter(i) {
	for (let j = i + 1; j < MAX_VIEWS; j++) {
		if (slots[j].state === 'empty' || slots[j].state === 'error') return j;
	}
	return -1;
}

function openPicker(index) {
	pickerTarget = index;
	els.fileInput.value = '';
	els.fileInput.click();
}

// Distribute dropped/picked files into slots, starting at `startIndex` (or the
// first free slot when null), filling free slots up to MAX_VIEWS.
function handleFiles(startIndex, fileList) {
	const files = Array.from(fileList).filter((f) => f && f.type && f.type.startsWith('image/'));
	if (!files.length) return;
	let idx = startIndex == null ? firstFreeSlot() : startIndex;
	for (const file of files) {
		if (idx < 0 || idx >= MAX_VIEWS) idx = firstFreeSlot();
		if (idx < 0) break; // all slots taken
		uploadToSlot(idx, file);
		idx = nextFreeAfter(idx);
	}
}

// Presign → PUT to object storage → public URL. Shared by the view slots and
// the sketch uploader. Returns { ok: true, url } or { ok: false, message }.
async function presignAndPut(file) {
	try {
		const presignRes = await fetch('/api/forge-upload', {
			method: 'POST',
			headers: { 'content-type': 'application/json', ...CLIENT_HEADERS },
			body: JSON.stringify({ content_type: file.type, size_bytes: file.size }),
		});
		const presign = await presignRes.json().catch(() => ({}));
		if (presignRes.status === 503) return { ok: false, message: 'Uploads unavailable — paste a URL.' };
		if (presignRes.status === 429) return { ok: false, message: 'Rate limited — retry shortly.' };
		if (!presignRes.ok || !presign.upload_url || !presign.public_url) {
			return { ok: false, message: presign.message || 'Upload failed.' };
		}

		const putRes = await fetch(presign.upload_url, {
			method: 'PUT',
			headers: { 'content-type': file.type },
			body: file,
		});
		if (!putRes.ok) return { ok: false, message: `Storage rejected the file (${putRes.status}).` };
		return { ok: true, url: presign.public_url };
	} catch {
		return { ok: false, message: 'Network error during upload.' };
	}
}

// Upload one file into a slot: presign → PUT to object storage → record the
// public URL. The slot moves empty/error → uploading → uploaded|error, each a
// real, designed state. The local blob preview shows immediately.
async function uploadToSlot(index, file) {
	if (!ACCEPTED_TYPES.has(file.type)) {
		setSlotError(index, 'Use PNG, JPG, or WebP.');
		return;
	}
	if (file.size > MAX_UPLOAD_BYTES) {
		setSlotError(index, 'Too large (max 8 MB).');
		return;
	}

	const prev = slots[index];
	if (prev.objectUrl) URL.revokeObjectURL(prev.objectUrl);
	const objectUrl = URL.createObjectURL(file);
	slots[index] = { state: 'uploading', url: null, objectUrl, errorMsg: '' };
	renderSlot(index);

	const up = await presignAndPut(file);
	if (!up.ok) {
		setSlotError(index, up.message);
		return;
	}
	// Success — keep the local blob preview, remember the public URL.
	slots[index] = { state: 'uploaded', url: up.url, objectUrl, errorMsg: '' };
	renderSlot(index);
}

function setSlotError(index, message) {
	const s = slots[index];
	// Keep any local preview so the user sees what failed.
	slots[index] = {
		state: 'error',
		url: null,
		objectUrl: s.objectUrl || null,
		errorMsg: message,
	};
	renderSlot(index);
}

function uploadedUrls() {
	return slots.filter((s) => s.state === 'uploaded' && s.url).map((s) => s.url);
}

// Sketch slot ------------------------------------------------------------------
// One drawing, built from the same .view-slot kit as the photo slots so every
// state (empty / uploading / uploaded / error) is already designed.

function sketchSlotEl() {
	return els.sketchGrid?.querySelector('.view-slot') || null;
}

function buildSketchSlot() {
	if (!els.sketchGrid || els.sketchGrid.childElementCount) return;
	const slot = document.createElement('div');
	slot.className = 'view-slot';
	slot.tabIndex = 0;
	slot.setAttribute('role', 'button');
	slot.innerHTML = `
		<div class="vs-empty">
			<span class="vs-icon" aria-hidden="true">✎</span>
			<span class="vs-label">Sketch</span>
		</div>
		<div class="vs-uploading">
			<div class="shimmer" aria-hidden="true"></div>
			<span>Uploading…</span>
		</div>
		<img class="vs-thumb" alt="" />
		<span class="vs-badge">Sketch</span>
		<button type="button" class="vs-remove" aria-label="Remove sketch">×</button>
		<div class="vs-error">
			<span class="vs-error-msg">Upload failed</span>
			<button type="button" class="vs-retry">Retry</button>
		</div>`;

	slot.querySelector('.vs-remove').addEventListener('click', (e) => {
		e.stopPropagation();
		clearSketch();
	});
	slot.querySelector('.vs-retry').addEventListener('click', (e) => {
		e.stopPropagation();
		openSketchPicker();
	});
	slot.addEventListener('click', () => {
		if (sketch.state === 'empty' || sketch.state === 'error') openSketchPicker();
	});
	slot.addEventListener('keydown', (e) => {
		if (e.key === 'Enter' || e.key === ' ') {
			e.preventDefault();
			if (sketch.state === 'empty' || sketch.state === 'error') openSketchPicker();
		}
	});
	slot.addEventListener('dragover', (e) => {
		e.preventDefault();
		e.dataTransfer.dropEffect = 'copy';
		slot.classList.add('drop-target');
	});
	slot.addEventListener('dragleave', () => slot.classList.remove('drop-target'));
	slot.addEventListener('drop', (e) => {
		e.preventDefault();
		slot.classList.remove('drop-target');
		const file = e.dataTransfer.files?.[0];
		if (file) uploadSketch(file);
	});

	els.sketchGrid.appendChild(slot);
	renderSketchSlot();
}

function openSketchPicker() {
	if (!els.sketchFileInput) return;
	els.sketchFileInput.value = '';
	els.sketchFileInput.click();
}

function renderSketchSlot() {
	const el = sketchSlotEl();
	if (!el) return;
	el.dataset.state = sketch.state;
	const img = el.querySelector('.vs-thumb');
	if (sketch.objectUrl) {
		img.src = sketch.objectUrl;
		img.alt = 'Your sketch';
	} else {
		img.removeAttribute('src');
		img.alt = '';
	}
	el.querySelector('.vs-error-msg').textContent = sketch.errorMsg || 'Upload failed';
	const labels = {
		empty: 'Sketch, empty — add a drawing',
		uploading: 'Sketch, uploading',
		uploaded: 'Sketch, uploaded',
		error: 'Sketch, upload failed',
	};
	el.setAttribute('aria-label', labels[sketch.state] || 'Sketch');
}

function clearSketch() {
	if (sketch.objectUrl) URL.revokeObjectURL(sketch.objectUrl);
	Object.assign(sketch, { state: 'empty', url: null, objectUrl: null, errorMsg: '' });
	renderSketchSlot();
}

async function uploadSketch(file) {
	if (!ACCEPTED_TYPES.has(file.type)) {
		Object.assign(sketch, { state: 'error', url: null, errorMsg: 'Use PNG, JPG, or WebP.' });
		renderSketchSlot();
		return;
	}
	if (file.size > MAX_UPLOAD_BYTES) {
		Object.assign(sketch, { state: 'error', url: null, errorMsg: 'Too large (max 8 MB).' });
		renderSketchSlot();
		return;
	}
	if (sketch.objectUrl) URL.revokeObjectURL(sketch.objectUrl);
	Object.assign(sketch, {
		state: 'uploading',
		url: null,
		objectUrl: URL.createObjectURL(file),
		errorMsg: '',
	});
	renderSketchSlot();

	const up = await presignAndPut(file);
	if (up.ok) Object.assign(sketch, { state: 'uploaded', url: up.url, errorMsg: '' });
	else Object.assign(sketch, { state: 'error', url: null, errorMsg: up.message });
	renderSketchSlot();
}

function firstPreviewUrl() {
	const s = slots.find((x) => x.state === 'uploaded' && (x.objectUrl || x.url));
	return s ? s.objectUrl || s.url : null;
}

// Job submission --------------------------------------------------------------

// Headers for a forge request, including the BYOK provider key (geometry path)
// when the user has entered one. The key rides a header, never the URL.
function forgeHeaders(extra) {
	const h = { ...CLIENT_HEADERS, ...extra };
	if (providerKey) h['x-forge-provider-key'] = providerKey;
	return h;
}

async function startJob({ prompt, imageUrls, skipValidation }) {
	const base = { path: selectedEngine.path, tier: selectedTier, backend: selectedEngine.backend };
	const body =
		Array.isArray(imageUrls) && imageUrls.length
			? { image_urls: imageUrls, prompt: prompt || undefined, ...base }
			: { prompt, aspect_ratio: aspectRatio, ...base };
	// Caller already saw the vision warning and chose to proceed (Consumer 1).
	if (skipValidation) body.skip_validation = true;

	const res = await fetch('/api/forge', {
		method: 'POST',
		headers: forgeHeaders({ 'content-type': 'application/json' }),
		body: JSON.stringify(body),
	});
	const data = await res.json().catch(() => ({}));
	if (res.status === 503 || data.error === 'unconfigured') {
		const e = new Error(data.message || 'unconfigured');
		e.kind = 'unconfigured';
		throw e;
	}
	// Geometry path needs a BYOK key we don't have — a recoverable, designed state.
	if (data.error === 'needs_key') {
		const e = new Error(data.message || 'An API key is required for this engine.');
		e.kind = 'needs_key';
		e.provider = data.provider;
		throw e;
	}
	if (data.error === 'invalid_key') {
		const e = new Error(data.message || 'The provider rejected this API key.');
		e.kind = 'invalid_key';
		throw e;
	}
	if (data.error === 'insufficient_credits') {
		const e = new Error(data.message || 'The provider account is out of credits.');
		e.kind = 'credits';
		throw e;
	}
	// Vision pre-check rejected the reference photo (Consumer 1). Recoverable:
	// the user can swap the photo (Try again) or override (Generate anyway).
	if (res.status === 422 && data.error === 'image_not_usable') {
		const e = new Error(data.message || 'That photo doesn’t look usable for 3D.');
		e.kind = 'not_usable';
		throw e;
	}
	if (res.status === 429 || data.error === 'rate_limited') {
		const secs = Number(data.retry_after) > 0 ? Math.ceil(Number(data.retry_after)) : 10;
		const e = new Error(
			data.message || `The 3D generator is busy. Try again in about ${secs} seconds.`,
		);
		e.kind = 'rate_limited';
		throw e;
	}
	if (!res.ok) {
		throw new Error(data.message || `The generator returned ${res.status}.`);
	}
	return data;
}

async function pollUntilDone(jobId) {
	const deadline = performance.now() + MAX_POLL_MS;
	while (!pollAbort && performance.now() < deadline) {
		await sleep(POLL_INTERVAL_MS);
		if (pollAbort) return null;
		const res = await fetch(`/api/forge?job=${encodeURIComponent(jobId)}`, {
			headers: forgeHeaders(),
		});
		const data = await res.json().catch(() => ({}));
		if (data.error === 'unconfigured') {
			const e = new Error(data.message || 'unconfigured');
			e.kind = 'unconfigured';
			throw e;
		}
		if (data.status === 'done' && data.glb_url) return data;
		if (data.status === 'failed') throw new Error(data.error || 'Generation failed.');
		if (data.status === 'running') setStep('mesh', 'active');
	}
	if (pollAbort) return null;
	throw new Error(
		'Generation timed out. The model may be too complex — try fewer views or a simpler prompt.',
	);
}

// Post the human verdict on a creation — the labeled half of the data flywheel.
function sendFeedback(payload) {
	if (!currentCreationId) return;
	fetch('/api/forge-feedback', {
		method: 'POST',
		headers: { 'content-type': 'application/json', ...CLIENT_HEADERS },
		body: JSON.stringify({ creation_id: currentCreationId, ...payload }),
		keepalive: true,
	}).catch(() => {});
}

function resetVerdict() {
	if (!els.verdict) return;
	for (const b of els.verdict.querySelectorAll('button')) {
		b.setAttribute('aria-pressed', 'false');
	}
}

// Poster capture — the visual half of every creation card. Image-intermediate
// engines store their flux reference image as the preview, but geometry-first
// and sketch lanes paint no image at all, so their gallery/showcase cards used
// to render as glyph placeholders. Once the finished mesh is standing in the
// viewer, render it onto a small studio-backdrop canvas and attach it to the
// creation row (POST /api/forge-poster — fill-only, owner-scoped, best-effort).
const POSTER_MAX_DIM = 640;
const postedPosters = new Set();

function renderPosterFrame(sourceDataUrl) {
	return new Promise((resolve) => {
		const img = new Image();
		img.onload = () => {
			const scale = Math.min(1, POSTER_MAX_DIM / Math.max(img.width, img.height, 1));
			const w = Math.max(1, Math.round(img.width * scale));
			const h = Math.max(1, Math.round(img.height * scale));
			const canvas = document.createElement('canvas');
			canvas.width = w;
			canvas.height = h;
			const ctx = canvas.getContext('2d');
			if (!ctx) return resolve(null);
			// Same studio backdrop as the live viewer, so mesh posters read as a
			// consistent set next to flux reference images in the galleries.
			const backdrop = ctx.createRadialGradient(w / 2, 0, 0, w / 2, 0, Math.max(w, h) * 1.2);
			backdrop.addColorStop(0, '#1a1612');
			backdrop.addColorStop(0.7, '#0b0a09');
			backdrop.addColorStop(1, '#0b0a09');
			ctx.fillStyle = backdrop;
			ctx.fillRect(0, 0, w, h);
			ctx.drawImage(img, 0, 0, w, h);
			const webp = canvas.toDataURL('image/webp', 0.85);
			// Browsers without webp encoding silently hand back PNG — send what we got.
			resolve(webp.startsWith('data:image/webp') ? webp : canvas.toDataURL('image/png'));
		};
		img.onerror = () => resolve(null);
		img.src = sourceDataUrl;
	});
}

async function capturePoster(creationId) {
	if (!creationId || postedPosters.has(creationId) || !els.viewer?.toDataURL) return;
	postedPosters.add(creationId);
	try {
		if (!els.viewer.loaded) {
			await new Promise((resolve) =>
				els.viewer.addEventListener('load', resolve, { once: true }),
			);
		}
		// Let the materialize entrance settle so the capture is a steady frame.
		await sleep(REDUCED_MOTION ? 300 : 1500);
		// A newer generation or an opened creation replaced the model — skip.
		if (currentCreationId !== creationId) return;
		const frame = await renderPosterFrame(els.viewer.toDataURL('image/png'));
		if (!frame) return;
		const res = await fetch('/api/forge-poster', {
			method: 'POST',
			headers: { 'content-type': 'application/json', ...CLIENT_HEADERS },
			body: JSON.stringify({ creation_id: creationId, image: frame }),
		});
		const data = await res.json().catch(() => ({}));
		// The card for this creation is already on screen with a placeholder —
		// refresh the strip so the new poster shows without a reload.
		if (data?.stored) loadGallery();
	} catch {
		// Best-effort: a missed poster never disturbs the result flow.
	}
}

// Render the provenance badge from job metadata: how the mesh was produced
// (engine + tier + path) plus any multi-view conditioning. Shows whatever is
// known — the geometry-first path has no reference views, the image path does.
function setViewsBadge(meta) {
	if (!els.resultViews) return;
	const parts = [];
	const used = Number(meta?.views_used);
	if (Number.isFinite(used) && used >= 1) {
		parts.push(`${used} ${used === 1 ? 'view' : 'views'}`);
		if (meta.multiview) parts.push('multi-view');
	}
	if (meta?.backend) parts.push(ENGINE_LABELS[meta.backend] || meta.backend);
	if (meta?.tier) parts.push(meta.tier);
	if (meta?.path === 'geometry') parts.push('geometry-first');
	if (meta?.path === 'sketch') parts.push('sketch→3D');
	if (parts.length === 0) {
		els.resultViews.classList.add('is-hidden');
		els.resultViews.textContent = '';
		return;
	}
	els.resultViews.textContent = parts.join(' · ');
	els.resultViews.classList.remove('is-hidden');
}

// Materialize entrance — conceal the standing viewer, play the WebGL dissolve
// reveal over it (src/forge-reveal.js), then crossfade back and hand the
// final camera angle to model-viewer so the turntable continues seamlessly.
// Presentation only: any failure restores the viewer immediately.
let revealSeq = 0;
async function playMaterialize(glbUrl) {
	if (REDUCED_MOTION || !els.viewerShell) return;
	const seq = ++revealSeq;
	els.viewer.style.opacity = '0';
	try {
		const { playForgeReveal } = await import('./forge-reveal.js');
		const viewerLoaded = new Promise((resolve) => {
			if (els.viewer.loaded) return resolve();
			els.viewer.addEventListener('load', resolve, { once: true });
		});
		const end = await playForgeReveal({
			container: els.viewerShell,
			glbUrl,
			waitFor: viewerLoaded,
		});
		if (seq === revealSeq && end && Number.isFinite(end.azimuthDeg)) {
			els.viewer.cameraOrbit = `${end.azimuthDeg.toFixed(1)}deg ${end.polarDeg.toFixed(1)}deg auto`;
		}
	} catch {
		// The standing viewer is the fallback — nothing to surface.
	} finally {
		if (seq === revealSeq) els.viewer.style.opacity = '1';
	}
}

// Show "Refine → <next tier>" only when a higher tier exists and the current
// result came from a job we can re-run (a prompt and/or reference images).
function updateRefineButton() {
	if (!els.refine) return;
	const next = nextTierAfter(currentResultTier);
	const reRunnable =
		lastJob && (lastJob.prompt || (Array.isArray(lastJob.imageUrls) && lastJob.imageUrls.length));
	const show = Boolean(next && reRunnable);
	els.refine.classList.toggle('is-hidden', !show);
	if (show) {
		els.refineLabel.textContent = `Refine → ${TIER_LABELS[next]}`;
		els.refine.title = `Re-run this exact ${
			lastJob.imageUrls?.length ? 'reconstruction' : 'prompt'
		} at ${TIER_LABELS[next]} quality`;
	}
}

function showResult(glbUrl, label, meta) {
	stopElapsed();
	resetVerdict();
	els.viewer.setAttribute('src', glbUrl);
	els.viewer.setAttribute('alt', `3D model: ${label}`);
	els.resultLabel.textContent = label;
	setViewsBadge(meta);
	els.download.href = glbUrl;
	els.download.setAttribute(
		'download',
		`${label.replace(/[^a-z0-9]+/gi, '-').slice(0, 48).replace(/^-|-$/g, '') || 'forge'}.glb`,
	);
	// Cross-link into Parts Studio with this exact model pre-loaded.
	if (els.segmentBtn) els.segmentBtn.href = `/segment?mesh=${encodeURIComponent(glbUrl)}`;
	// Offer "Refine" when a higher tier exists and this job can be re-run. Use the
	// tier the result was actually produced at (meta), falling back to the current
	// selection for re-opened gallery models that don't carry tier metadata.
	currentResultTier = meta?.tier || selectedTier;
	updateRefineButton();
	showState('result');
	playMaterialize(glbUrl);
	// Hand the live model to the Stylize panel (src/forge-stylize.js) so its
	// one-click geometric filters operate on the current source mesh.
	document.dispatchEvent(
		new CustomEvent('forge:model-ready', { detail: { glbUrl, label } }),
	);
	document.dispatchEvent(
		new CustomEvent('tws:feature-done', {
			detail: { feature: 'forge', model: { glbUrl, label } },
		}),
	);
	if (els.forgeShareBtn) {
		els.forgeShareBtn.dataset.sharePrompt = label;
	}
}

// Load (or reload) the "Your creations" strip from durable storage.
async function loadGallery() {
	if (!els.creations) return;

	els.creations.classList.remove('is-hidden');
	els.creationsGrid.setAttribute('aria-busy', 'true');
	els.creationsGrid.innerHTML = skeletonHTML(4, 'card');

	let data;
	try {
		const res = await fetch('/api/forge-gallery?limit=24', { headers: CLIENT_HEADERS });
		data = await res.json().catch(() => ({}));
	} catch {
		els.creationsGrid.removeAttribute('aria-busy');
		els.creationsGrid.innerHTML = errorStateHTML({
			title: "Couldn't load your creations",
			body: 'Check your connection — your models are still saved.',
		});
		els.creationsGrid.querySelector('[data-sk-retry]')?.addEventListener('click', loadGallery);
		return;
	}

	els.creationsGrid.removeAttribute('aria-busy');
	const creations = Array.isArray(data?.creations) ? data.creations : [];
	if (!data?.enabled || creations.length === 0) {
		els.creations.classList.add('is-hidden');
		return;
	}
	els.creationsGrid.innerHTML = '';
	for (const c of creations) {
		const card = document.createElement('button');
		card.type = 'button';
		card.className = 'creation';
		card.title = c.prompt || 'Forged model';
		card.setAttribute('aria-label', `Open: ${c.prompt || 'forged model'}`);
		if (c.id) card.dataset.creationId = c.id;

		if (c.preview_image_url) {
			const img = document.createElement('img');
			img.className = 'thumb';
			img.loading = 'lazy';
			img.alt = '';
			img.src = c.preview_image_url;
			card.appendChild(img);
		} else {
			const ph = document.createElement('span');
			ph.className = 'thumb placeholder';
			ph.textContent = '◳';
			card.appendChild(ph);
		}

		if (c.outcome === 'accepted' || c.outcome === 'rejected') {
			const badge = document.createElement('span');
			badge.className = 'badge';
			badge.dataset.outcome = c.outcome;
			badge.textContent = c.outcome === 'accepted' ? '👍' : '👎';
			card.appendChild(badge);
		}

		// Surface multi-view provenance so the gallery reflects how each model
		// was conditioned.
		if (Number(c.views_used) > 1) {
			const mv = document.createElement('span');
			mv.className = 'badge';
			mv.style.left = '6px';
			mv.style.right = 'auto';
			mv.textContent = `${c.views_used}×`;
			mv.title = `${c.views_used} reference views`;
			card.appendChild(mv);
		}

		// Engine · tier provenance, so the gallery reflects how each was made.
		if (c.backend || c.tier) {
			const prov = document.createElement('span');
			prov.className = 'badge';
			prov.style.left = '6px';
			prov.style.right = 'auto';
			prov.style.top = Number(c.views_used) > 1 ? '28px' : '6px';
			prov.textContent = [ENGINE_LABELS[c.backend] || c.backend, c.tier].filter(Boolean).join(' ');
			prov.title =
				`${c.path === 'geometry' ? 'Geometry-first' : c.path === 'sketch' ? 'Sketch→3D' : 'Image path'} · ${c.backend || ''} · ${c.tier || ''}`.trim();
			card.appendChild(prov);
		}

		const meta = document.createElement('span');
		meta.className = 'meta';
		meta.textContent = c.prompt || 'Untitled';
		card.appendChild(meta);

		card.addEventListener('click', () => openCreation(c));

		els.creationsGrid.appendChild(card);
	}
	els.creationsCount.textContent = `${creations.length} saved`;
	els.creations.classList.remove('is-hidden');
}

// Load a creation into the viewer — shared by gallery card clicks and the
// share-link path. `c` is a creation row from /api/forge-gallery or
// /api/forge-creation; both return the same shape.
function openCreation(c, { scroll = true } = {}) {
	currentCreationId = c.id;
	lastJob = { prompt: c.prompt || '', imageUrls: [] };
	showResult(c.glb_url, c.prompt || 'Forged model', {
		views_used: c.views_used,
		multiview: c.multiview,
		backend: c.backend,
		tier: c.tier,
		path: c.path,
	});
	if (els.verdict) {
		for (const b of els.verdict.querySelectorAll('button')) {
			b.setAttribute('aria-pressed', String(b.dataset.outcome === c.outcome));
		}
	}
	if (scroll) els.stage.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// Open a creation from a share link. The model belongs to whoever forged it, so
// it won't be in this browser's gallery — fetch it directly by id. If the card
// is already present (the owner re-opening their own share link), reuse it.
async function openSharedCreation(shareId) {
	const card = els.creationsGrid?.querySelector(`[data-creation-id="${shareId}"]`);
	if (card) {
		card.click();
		card.scrollIntoView({ behavior: 'smooth', block: 'center' });
		return;
	}
	let creation = null;
	try {
		const res = await fetch(`/api/forge-creation?id=${encodeURIComponent(shareId)}`, {
			headers: CLIENT_HEADERS,
		});
		const data = await res.json().catch(() => ({}));
		creation = data?.creation || null;
	} catch {
		creation = null;
	}
	if (creation?.glb_url) {
		openCreation(creation);
	} else {
		showError(
			"This shared creation isn't available — it may have been removed or is still generating.",
		);
	}
}

function showError(message, { allowOverride = false } = {}) {
	stopElapsed();
	els.errorMessage.textContent = message;
	// The "Generate anyway" affordance only exists for the vision pre-check
	// rejection; every other error hides it so it can't leak across states.
	if (els.generateAnyway) els.generateAnyway.classList.toggle('is-hidden', !allowOverride);
	showState('error');
}

// Run a job (text or image/multi-view). `cfg` = { prompt, imageUrls }.
async function run(cfg) {
	lastJob = cfg;
	pollAbort = false;
	currentCreationId = null;
	setBusy(true);

	const isImage = Array.isArray(cfg.imageUrls) && cfg.imageUrls.length > 0;
	const isGeometry = selectedEngine.path === 'geometry';
	const isSketch = selectedEngine.path === 'sketch';
	const meshLabel = `Generating ${selectedTier} mesh`;

	// Reset the generating panel to its real starting state for this run.
	if (isSketch) {
		// The drawing IS the reference — no synthesis step, straight to geometry.
		setStepLabel('image', 'Sketch uploaded');
		setStepLabel('mesh', `Generating ${selectedTier} geometry from the sketch`);
		setStep('image', 'done');
		setStep('mesh', 'active');
		const preview = sketch.objectUrl || sketch.url;
		els.genPreview.innerHTML = preview ? '' : '<div class="shimmer" aria-hidden="true"></div>';
		if (preview) {
			const img = new Image();
			img.alt = 'Your sketch';
			img.src = preview;
			els.genPreview.appendChild(img);
		}
	} else if (isImage) {
		const n = cfg.imageUrls.length;
		setStepLabel('image', `Conditioning on ${n} ${n === 1 ? 'view' : 'views'}`);
		setStepLabel('mesh', isGeometry ? meshLabel : 'Reconstructing textured mesh');
		setStep('image', 'done');
		setStep('mesh', 'active');
		const preview = firstPreviewUrl();
		els.genPreview.innerHTML = preview ? '' : '<div class="shimmer" aria-hidden="true"></div>';
		if (preview) {
			const img = new Image();
			img.alt = 'Reference view';
			img.src = preview;
			els.genPreview.appendChild(img);
		}
	} else if (isGeometry) {
		// Geometry-first: no reference image is painted — the model emits geometry
		// straight from the prompt, so the first step is already complete.
		setStepLabel('image', 'Geometry-first — no reference image');
		setStepLabel('mesh', meshLabel);
		setStep('image', 'done');
		setStep('mesh', 'active');
		els.genPreview.innerHTML = '<div class="shimmer" aria-hidden="true"></div>';
	} else {
		setStepLabel('image', 'Painting reference image');
		setStepLabel('mesh', 'Reconstructing textured mesh');
		els.genPreview.innerHTML = '<div class="shimmer" aria-hidden="true"></div>';
		setStep('image', 'active');
		setStep('mesh', 'pending');
	}
	setStep('finish', 'pending');
	startElapsed();
	showState('generating');

	const label = cfg.prompt || (isImage ? 'Multi-view reconstruction' : '');

	try {
		const job = await startJob(cfg);
		if (job.creation_id) currentCreationId = job.creation_id;

		// Text→3D: the reference image resolved before the POST returned — show it.
		if (!isImage && job.preview_image_url) {
			setStep('image', 'done');
			setStep('mesh', 'active');
			const img = new Image();
			img.alt = 'Reference image';
			img.src = job.preview_image_url;
			img.onload = () => {
				els.genPreview.innerHTML = '';
				els.genPreview.appendChild(img);
			};
		}

		// The free draft lane (NVIDIA NIM) completes synchronously — the POST
		// itself returns the finished model with a null job_id. Polling that
		// null id would loop on invalid_job until the timeout, losing a result
		// that already succeeded.
		const done =
			job.status === 'done' && job.glb_url ? job : await pollUntilDone(job.job_id);
		if (pollAbort || !done) return; // cancelled

		if (done.creation_id) currentCreationId = done.creation_id;
		setStep('mesh', 'done');
		setStep('finish', 'done');
		markProgressDone();
		// Prefer the poll's recorded meta; fall back to the submit response.
		showResult(done.glb_url, label || 'Forged model', {
			views_used: done.views_used ?? job.views_used,
			multiview: done.multiview ?? job.multiview,
			backend: done.backend ?? job.backend,
			tier: done.tier ?? job.tier,
			path: done.path ?? job.path,
		});
		loadGallery();
		// Geometry-first and sketch lanes have no reference image — render the
		// finished mesh itself as the creation's card visual.
		if (!(done.preview_image_url ?? job.preview_image_url)) {
			capturePoster(currentCreationId);
		}
	} catch (err) {
		if (pollAbort) return;
		if (err.kind === 'unconfigured') {
			stopElapsed();
			showState('unconfigured');
			return;
		}
		// Recoverable BYOK problems — reveal + focus the key field so the user can
		// fix it and hit Retry, rather than hitting a dead end.
		if (err.kind === 'needs_key' || err.kind === 'invalid_key') {
			stopElapsed();
			els.byokRow?.classList.remove('is-hidden');
			if (els.providerKey) {
				els.providerKey.setAttribute('aria-invalid', 'true');
				els.providerKey.focus();
			}
			showError(err.message || 'Add your API key to use this engine, then retry.');
			return;
		}
		if (err.kind === 'credits') {
			stopElapsed();
			showError(err.message || 'The provider account is out of credits.');
			return;
		}
		// The reference photo failed the vision pre-check. Offer "Generate anyway"
		// so a confident user is never permanently blocked by a cautious verdict.
		if (err.kind === 'not_usable') {
			showError(err.message, { allowOverride: true });
			return;
		}
		showError(
			err.message ||
				'Something went wrong. Try a simpler, single-subject prompt or cleaner photos.',
		);
	} finally {
		setBusy(false);
	}
}

function submit() {
	if (mode === 'text') {
		const prompt = els.prompt.value.trim();
		if (prompt.length < 3) {
			els.prompt.focus();
			return;
		}
		run({ prompt, imageUrls: [] });
		return;
	}

	// Sketch mode — one drawing + a required prompt naming what it depicts.
	if (mode === 'sketch') {
		if (sketch.state === 'uploading') {
			els.generateLabel.textContent = 'Waiting for upload…';
			setTimeout(() => {
				if (!els.generate.disabled) els.generateLabel.textContent = 'Generate';
			}, 1600);
			return;
		}
		if (sketch.state !== 'uploaded' || !sketch.url) {
			const slot = sketchSlotEl();
			slot?.focus();
			slot?.classList.add('drop-target');
			setTimeout(() => slot?.classList.remove('drop-target'), 600);
			return;
		}
		const prompt = els.sketchPrompt.value.trim();
		if (prompt.length < 3) {
			// Make the required-input contract unmissable: flag the field and tint
			// the "Required" tag until the user types a description.
			els.sketchPrompt.setAttribute('aria-invalid', 'true');
			if (els.sketchReqTag) els.sketchReqTag.dataset.missing = 'true';
			els.sketchPrompt.focus();
			return;
		}
		run({ prompt, imageUrls: [sketch.url] });
		return;
	}

	// Image / multi-view mode.
	if (slots.some((s) => s.state === 'uploading')) {
		els.generateLabel.textContent = 'Waiting for uploads…';
		setTimeout(() => {
			if (!els.generate.disabled) els.generateLabel.textContent = 'Generate';
		}, 1600);
		return;
	}
	const urls = uploadedUrls();
	if (urls.length === 0) {
		const first = slotEl(0);
		first?.focus();
		first?.classList.add('drop-target');
		setTimeout(() => first?.classList.remove('drop-target'), 600);
		return;
	}
	run({ prompt: els.imagePrompt.value.trim(), imageUrls: urls });
}

// Wiring ----------------------------------------------------------------------

buildSlots();
buildViewsPips();
updateViewsCounter();

els.modeSwitch.addEventListener('click', (e) => {
	const btn = e.target.closest('button[data-mode]');
	if (btn) setMode(btn.dataset.mode);
});

els.fileInput.addEventListener('change', () => {
	handleFiles(pickerTarget, els.fileInput.files);
	pickerTarget = null;
	els.fileInput.value = '';
});

els.form.addEventListener('submit', (e) => {
	e.preventDefault();
	submit();
});

// Cmd/Ctrl+Enter submits from either text box.
function submitOnModifierEnter(e) {
	if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
		e.preventDefault();
		submit();
	}
}
els.prompt.addEventListener('keydown', submitOnModifierEnter);
els.imagePrompt.addEventListener('keydown', submitOnModifierEnter);
els.sketchPrompt?.addEventListener('keydown', submitOnModifierEnter);

// Typing into the sketch prompt clears the "required" warning state.
els.sketchPrompt?.addEventListener('input', () => {
	els.sketchPrompt.removeAttribute('aria-invalid');
	if (els.sketchReqTag) els.sketchReqTag.dataset.missing = 'false';
});

els.sketchFileInput?.addEventListener('change', () => {
	const file = els.sketchFileInput.files?.[0];
	if (file) uploadSketch(file);
	els.sketchFileInput.value = '';
});

els.aspect.addEventListener('click', (e) => {
	const btn = e.target.closest('button[data-aspect]');
	if (!btn) return;
	aspectRatio = btn.dataset.aspect;
	for (const b of els.aspect.querySelectorAll('button')) {
		b.setAttribute('aria-pressed', String(b === btn));
	}
});

els.examples.addEventListener('click', (e) => {
	const chip = e.target.closest('.chip');
	if (!chip) return;
	setMode('text');
	els.prompt.value = chip.textContent.trim();
	els.prompt.focus();
	submit();
});

// Quality tier + engine + BYOK key wiring.
els.tier?.addEventListener('click', (e) => {
	const btn = e.target.closest('button[data-tier]');
	if (btn) selectTier(btn.dataset.tier);
});
els.engine?.addEventListener('click', (e) => {
	const btn = e.target.closest('button[data-engine]');
	if (btn && !btn.disabled) {
		userPickedEngine = true;
		selectEngine(btn);
	}
});
els.providerKey?.addEventListener('input', () => {
	providerKey = els.providerKey.value.trim();
	els.providerKey.removeAttribute('aria-invalid');
});

els.cancel.addEventListener('click', () => {
	pollAbort = true;
	stopElapsed();
	setBusy(false);
	showState('empty');
});

els.again.addEventListener('click', () => {
	showState('empty');
	if (mode === 'text') {
		els.prompt.focus();
		els.prompt.select();
	} else if (mode === 'sketch') {
		(sketch.state === 'uploaded' ? els.sketchPrompt : sketchSlotEl())?.focus();
	} else {
		slotEl(0)?.focus();
	}
});

els.retry.addEventListener('click', () => {
	if (lastJob && (lastJob.prompt || (lastJob.imageUrls && lastJob.imageUrls.length))) {
		run(lastJob);
	} else {
		showState('empty');
		els.prompt.focus();
	}
});

// Refine — re-run the same prompt/views one quality tier higher. Bumping the
// tier syncs the selector (and the tier's default engine), then replays the
// stored job, so the higher-fidelity model lands in the same viewer.
els.refine?.addEventListener('click', () => {
	const next = nextTierAfter(currentResultTier);
	if (!next || !lastJob) return;
	selectTier(next);
	run(lastJob);
});

// "Generate anyway" — re-run the same job with the vision pre-check bypassed.
els.generateAnyway?.addEventListener('click', () => {
	if (!lastJob) return;
	run({ ...lastJob, skipValidation: true });
});

if (els.verdict) {
	els.verdict.addEventListener('click', (e) => {
		const btn = e.target.closest('button[data-outcome]');
		if (!btn || !currentCreationId) return;
		const outcome = btn.dataset.outcome;
		for (const b of els.verdict.querySelectorAll('button')) {
			b.setAttribute('aria-pressed', String(b === btn));
		}
		sendFeedback({ outcome });
	});
}

// Downloads route through a provenance pass: fetch the GLB, stamp
// asset.generator + asset.extras (source, prompt) into the JSON chunk, and
// hand the user the stamped file. Any failure falls back to the raw provider
// file — stamping must never block a download.
els.download.addEventListener('click', async (e) => {
	sendFeedback({ downloaded: true });
	const glbUrl = els.download.href;
	if (!glbUrl || glbUrl.startsWith('blob:') || els.download.dataset.stamping) return;
	e.preventDefault();
	els.download.dataset.stamping = '1';
	const filename = els.download.getAttribute('download') || 'forge.glb';
	try {
		const res = await fetch(glbUrl);
		if (!res.ok) throw new Error(`fetch ${res.status}`);
		const stamped = stampGlbAttribution(await res.arrayBuffer(), {
			prompt: els.resultLabel?.textContent || '',
		});
		const blobUrl = URL.createObjectURL(new Blob([stamped], { type: 'model/gltf-binary' }));
		const a = document.createElement('a');
		a.href = blobUrl;
		a.download = filename;
		a.click();
		setTimeout(() => URL.revokeObjectURL(blobUrl), 30_000);
	} catch {
		const a = document.createElement('a');
		a.href = glbUrl;
		a.download = filename;
		a.click();
	} finally {
		delete els.download.dataset.stamping;
	}
});

els.cinema?.addEventListener('click', () => setCinema(!cinemaOn));

document.addEventListener('keydown', (e) => {
	if (e.key === 'Escape' && cinemaOn) {
		setCinema(false);
		return;
	}
	if (e.metaKey || e.ctrlKey || e.altKey) return;
	const active = document.activeElement;
	if (active?.tagName === 'INPUT' || active?.tagName === 'TEXTAREA' || active?.isContentEditable)
		return;
	// "/" jumps to the prompt for the current mode — the standard quick-focus.
	if (e.key === '/') {
		e.preventDefault();
		const box = mode === 'sketch' ? els.sketchPrompt : mode === 'image' ? els.imagePrompt : els.prompt;
		box?.focus();
		return;
	}
	if (e.key !== 'f' && e.key !== 'F') return;
	if (els.states.result.classList.contains('is-hidden')) return;
	e.preventDefault();
	setCinema(!cinemaOn);
});

if (els.forgeShareBtn) {
	els.forgeShareBtn.addEventListener('click', () => {
		const origin = location.origin;
		const prompt = els.forgeShareBtn.dataset.sharePrompt || lastJob?.prompt || '';
		const id = currentCreationId;
		const shareUrl = id ? `${origin}/forge/share/${id}` : `${origin}/forge`;
		const remixUrl = prompt
			? `${origin}/forge?prompt=${encodeURIComponent(prompt)}`
			: `${origin}/forge`;
		showSharePanel(
			{
				kind: 'forge',
				id: id || '',
				title: prompt || 'Forged creation',
				description: 'A 3D model generated with text / image → 3D on three.ws',
				shareUrl,
				remixUrl,
			},
			els.forgeShareBtn,
		);
	});
}

// Handle ?prompt= (pre-fill from a remix link) and ?share= (open a creation).
(function handleQueryParams() {
	const params = new URLSearchParams(location.search);
	const promptParam = params.get('prompt');
	const shareParam = params.get('share');
	if (promptParam && els.prompt) {
		setMode('text');
		els.prompt.value = decodeURIComponent(promptParam).slice(0, 300);
		els.prompt.focus();
	}
	if (shareParam) {
		window.__forgeShareId = shareParam;
	}
})();

// Hooks for the companion modules (forge-dropzone.js, forge-showcase.js) —
// a CustomEvent contract keeps them decoupled from this file's internals.

// Images captured anywhere on the page (clipboard paste, page-level drop).
// In sketch mode a single image becomes the sketch; otherwise we switch to
// photo mode and distribute into free view slots.
document.addEventListener('forge:add-images', (e) => {
	const files = Array.isArray(e.detail?.files) ? e.detail.files : [];
	if (!files.length) return;
	if (mode === 'sketch' && files.length === 1) {
		uploadSketch(files[0]);
		return;
	}
	if (mode !== 'image') setMode('image');
	handleFiles(null, files);
});

// A community-showcase card asks to open its creation in the main viewer, so
// the full result bar (download, share, stylize, optimize, split) works on it.
document.addEventListener('forge:open-creation', (e) => {
	const creation = e.detail?.creation;
	if (creation?.glb_url) openCreation(creation);
});

// Build the quality/engine controls from the live catalog (tiers, backends,
// cost/time matrix). Falls back silently to the defaults if it can't load.
loadCatalog();

// Surface any previously forged models for this browser on load.
loadGallery().then(() => {
	const shareId = window.__forgeShareId;
	if (shareId) openSharedCreation(shareId);
});
